### ISSUE TITLE
sblookup network failure always returns "Safe URL"

### ISSUE THREAD

**Issue by donfranke** [google/safebrowsing#13]
If running sblookup without network connectivity, URL check will always return "Safe URL".  Changing line 91 to make if statement above to if-else (and adding a 'no network' message above it) ensures failed lookup always returns "Unsafe URL", which is the more secure default.

**Comment by dsnet** [comment]
If I may ask, Line 91 of which file?

**Comment by dsnet** [comment]
Ah, I see what you mean. I'll fix this. Thanks for the report.

**Comment by donfranke** [comment]
No problem. Just in case it's safebrowsing/cmd/sblookup/main.go
