### ISSUE TITLE
sbserver memory usage question

### ISSUE THREAD

**Issue by bgv** [google/safebrowsing#17]
Is it normal for sbserver to use so much memory? On startup it eats away 455MiB

```
newton:~ bgv$ sbserver -db ~/tmp/sbserver.db -apikey XXX
safebrowsing: 2016/06/08 13:16:09 database.go:96: load failure: open /Users/bgv/tmp/sbserver.db: no such file or directory
safebrowsing: 2016/06/08 13:16:13 database.go:259: database is now healthy
Starting server at localhost:8080
```
```
newton:~ bgv$ ps -o pcpu=,rss=,vsz= -p 5307
  0.0 465968 573526448
```
  
Few db updates later it's already allocated whooping 1.4GiB
```
newton:~ bgv$ ps -o pcpu=,rss=,vsz= -p 5307
  0.0 1534480 573526448
```

**Comment by shahbag** [comment]
The database ~/tmp/sbserver.db should be only few megabytes. The memory usage by ps I believe is only reserved memory. Go reserves a bit more but manages better. You can read about Go's garbage collection. @dsnet do you know a good one?

**Comment by dsnet** [comment]
Using [`runtime.ReadMemStats`](https://golang.org/pkg/runtime/#ReadMemStats) to read the memory stats from the Go runtime, we see that the code is indeed holding onto a tremendous amount of memory.

These stats were measured before and after the DB was updated (calling runtime.GC() to force a GC cycle before reading the stats).

Before calling `database.Update`:
```go
runtime.MemStats{
	Alloc:         299624, // bytes allocated and not yet freed
	TotalAlloc:    363192, // bytes allocated (even if freed)
	Sys:          4983032, // bytes obtained from system
	Lookups:            5, // number of pointer lookups
	Mallocs:         5087, // number of mallocs
	Frees:             28, // number of frees
	...
}
```

After calling `database.Update`:
```go
runtime.MemStats{
	Alloc:       389915248, // bytes allocated and not yet freed 
	TotalAlloc:  546027112, // bytes allocated (even if freed) 
	Sys:         422515344, // bytes obtained from system 
	Lookups:            22, // number of pointer lookups 
	Mallocs:       6785242, // number of mallocs 
	Frees:          187824, // number of frees
	...
}
```

Going from 3MB => 390MB after `database.Update` is pretty indicated that the database is the culprit (surprise surprise!).

I certainly expect some factor greater than the uncompressed, serialized size of the database (which is ~8MB), but 400MB is much larger than I expected.

There is certainly something going on here and it is worth investigating.

**Comment by bgv** [comment]
@shahbag I'm not worried about the database it is indeed tiny as for the observed memory usage it's certainly not standard Go behaviour!

@dsnet Exactly, after 3-4 updates it went to almost 1.5GiB sat there since, but still quite fascinating appetite for RAM

**Comment by dsnet** [comment]
Some other statistics, the database contains 1.65 million partial hashes, where the average length of each partial hash is 4 bytes. However, the `string` data structure in Go is 16B long on 64 bit systems, meaning we already have an expansion of ~5x at least.

I haven't done the math for the `map` data structures, but I wouldn't be surprised we're taking a tremendous hit storing the pointers to all these short lengths of bytes.

**Comment by dsnet** [comment]
Commit 7651af5723cff1f5a08f5497a40eae682860be91 is one step forward in addressing this. Still more steps to make.

**Comment by bgv** [comment]
This is much better indeed on first update!

However subsequent db updates grow the usage to over 600MiB, not as bad as 1.4GiB before though :)

**Comment by dsnet** [comment]
The pull request I have outstanding should resolve this issue. You can read the description for the optimizations made.

Here is what the memory profile looks like after going through 10 list update cycles:
```
Alloc: 24MiB
Sys: 118MiB
HeapAlloc: 24MiB
HeapSys: 109MiB
```

This is the same profile prior to the optimization:
```
Alloc: 488MiB
Sys: 1GiB
HeapAlloc: 488MiB
HeapSys: 1GiB
```

I think a 20x decrease in a memory reduction since this issue was filed is considered good enough.

**Comment by bgv** [comment]
@dsnet Looks good to me and it's definitely good enough, gave the changes a real world test for the past few days and it's much more gentle on memory after subsequent db updates.

Once the pull request changes will make it on the main repo I'm more than happy to close this issue.
