### ISSUE TITLE
only ThreatEntry.Url may be set

### ISSUE THREAD

**Issue by soothsayer011** [google/safebrowsing#23]
I receive this "only ThreatEntry.Url may be set" when I try to scan a large set of urls, like 20,000. There is nothing wrong with the format of the json file I post. If I limit the number of urls to about 1,100ish, everything works fine. It's like it doesn't recognize the set as being a list URLs but maybe url hashes or something.

**Comment by dsnet** [comment]
In `cmd/sbserver/main.go`, it does the following check on L354:
```
if u.Url == "" || len(u.Hash) > 0 {
	http.Error(resp, "only ThreatEntry.Url may be set", http.StatusBadRequest)
	return
}
```

Are you passing in an empty URL?

**Comment by soothsayer011** [comment]
I am just now seeing this block. I don't think I am passing an empty url, but the only explanation is that I am based on that block of code. I will check the URLs in the json file. Thank you for the comment. 

I consider this ticket closed.
