### ISSUE TITLE
update API doesn't check minimumWaitDuration 

### ISSUE THREAD

**Issue by matthpl** [google/safebrowsing#33]
[https://developers.google.com/safe-browsing/v4/request-frequency#minimum-wait-duration](url)
According to the spec, 

> Both the fullHashes.find response and threatListUpdates.fetch response have a minimumWaitDuration field that clients must obey. 

If a lot of clients are sending requests and the server has to call excessive api.HashLookup(), will the server result in receiving a response with minimumWaitDuration?

I think the server should check if the response contain minimumWaitDuration.

will sending excessive  "fullHashes.find" cause receiving minimumWaitDuration in response?

**Comment by dsnet** [comment]
@alexwoz. This is a known issue that the code currently doesn't respect the minimum wait duration.

**Comment by cpu** [comment]
I believe this issue can be closed now that #49 has merged.
