### ISSUE TITLE
Back-off mode

### ISSUE THREAD

**Issue by smoya** [google/safebrowsing#37]
According to the [docs](https://developers.google.com/safe-browsing/v4/request-frequency#back-off-mode):

> Clients that receive an unsuccessful HTTP response (that is, any HTTP status code other than 200 OK) must enter back-off mode. Once in back-off mode, clients must wait the computed time duration before they can issue another request to the server.

Let's suppose we receive a 500 error from the Update API:
* api.go returns the error on **ListUpdate** method.
* database.go sets that error on the database doing **db.setError** in the **Update** method.

It should then enter in back-off mode but it seems is not (at least i can not find it in the code). 

Apart from that, the application remains useless until the next Update (30 mins), which process could also return another 500 error and so on. There is any solution to this?

Thanks

**Comment by cpu** [comment]
I believe this issue can be closed now that #49 has merged.

**Comment by 3kt** [comment]
Again, according to the [documentation](https://developers.google.com/safe-browsing/v4/request-frequency):

> Automatic back-off applies to both the fullHashes.find response and threatListUpdates.fetch response.

So far, the BO mode only seem to cover the database update.

However, does it make sense to block all server calls for at least 15 minutes after each 4xx or 5xx response?
