### ISSUE TITLE
Which database is being used to persist the hashes ?

### ISSUE THREAD

**Issue by priyankatanvani** [google/safebrowsing#42]
In the code i see that the hashes are being persisted to file and on startup the db is being populated from previously existing file. 
What are these files ? Can they be normal text files ?
I'm not familiar with go that's why i'm facing trouble understanding the code.

**Comment by colonelxc** [comment]
As mentioned in another issue, the "database" is just the in-memory structure containing hash prefixes and other blacklist metadata. As far as saving/loading files goes, the code is using the [gob](https://golang.org/pkg/encoding/gob/) package, which serializes a Go data structure into a binary format. In addition, the file is gzipped to save space. So the in-memory structure is being serialized and compressed as it is written to the disk.

**Comment by dsnet** [comment]
The "another issue" in question is #21
