### ISSUE TITLE
Non-persistent mode expects database to be present

### ISSUE THREAD

**Issue by inge4pres** [google/safebrowsing#43]
Hi,

I am trying to use this configuration to create a client
```
mykey := os.Getenv("SB_KEY")
conf := &sb.Config{
		APIKey:    mykey,
		Logger:    os.Stdout,
		ThreatLists: []sb.ThreatDescriptor{
			sb.ThreatDescriptor{
				ThreatType:   sb.ThreatType_Malware,
				PlatformType: sb.PlatformType_AllPlatforms,
			},
		},
	}
client, err := sb.NewSafeBrowser(*conf)
...
threats, err := client.LookupURLs([]string{url})
...
```
When running tests I get this error
```
safebrowsing: 2017/01/04 14:53:06 database.go:186: ListUpdate failure: safebrowsing: unexpected server response code: 404
safebrowsing: 2017/01/04 14:53:06 safebrowser.go:365: inconsistent database: safebrowsing: unexpected server response code: 404
```

And looking at the source it seems that it will try to ListUpdate() every request.
What is the right way of running the lookup like documented [here](https://developers.google.com/safe-browsing/v4/lookup-api)?

Thank You

**Comment by dsnet** [comment]
I just tried running this on my machine and with the `url` set to something like "http://google.com" it printed the following:
```
safebrowsing: 2017/01/04 09:37:36 database.go:100: no database file specified
safebrowsing: 2017/01/04 09:37:38 database.go:291: database is now healthy
Results: [[]]
```

I'm surprised that you get 404 errors since nothing in your `Config` struct changed the `ServerURL` field.
What revision are you running on? Do you have any local changes?

**Comment by inge4pres** [comment]
Hi @dsnet  thanks for your support.
I grabbed the code with `go get github.com/google/safebrowsing` and did no changes to the source code.
Tried again now with the same config and got
```
=== RUN   TestCheckMaliciousURL
safebrowsing: 2017/01/07 12:26:40 database.go:100: no database file specified
safebrowsing: 2017/01/07 12:26:40 database.go:186: ListUpdate failure: safebrowsing: unexpected server response code: 404
safebrowsing: 2017/01/07 12:26:40 safebrowser.go:365: inconsistent database: safebrowsing: unexpected server response code: 404
--- FAIL: TestCheckMaliciousURL (0.14s)
	post_test.go:26: safebrowsing: unexpected server response code: 404
```
with a valid URL with trailing slash.
I am on Windows, maybe this is the issue? :)

**Comment by inge4pres** [comment]
I resolved it by removing the ThreatList from the config, don't know why exactly.
