### ISSUE TITLE
safebrowsing api query result is not consistent with chrome browser?

### ISSUE THREAD

**Issue by yinziyang** [google/safebrowsing#60]
When I use safebrowsing api to query the url "http://0.99730.von1.com/", query result is safe url, but in chrome, query result is unsafe.

I use sblookup cmd to check the url:

`echo "http://0.99730.von1.com/" | sblookup -apikey=$MY_API_KEY`
safebrowsing: 2017/06/02 18:15:10 database.go:106: no database file specified
safebrowsing: 2017/06/02 18:15:11 database.go:229: Server requested next update in 30m25.5s
safebrowsing: 2017/06/02 18:15:11 database.go:336: database is now healthy
**`Safe URL: http://0.99730.von1.com/`**

**Comment by yinziyang** [comment]
same issue like #30, I closed this issue.

**Comment by jodevsa** [comment]
why closed if the problem still exists ?

**Comment by dsnet** [comment]
Because duplicate issues are not helpful when people start making discussions about the same thing across different issues.

**Comment by jodevsa** [comment]
at least provide a status? when it's going to be fixed
