### ISSUE TITLE
invalid compression type

### ISSUE THREAD

**Issue by Fedwin** [google/safebrowsing#63]
Since 17.6. 12:00 AM CET all requests are answered with 500 server error:

`safebrowsing: 2017/07/18 13:08:16 safebrowser.go:372: inconsistent database: safebrowsing: invalid compression type`

Test URL:

`curl localhost:8221/r?url=heise.de`

We used the Safe Browsing API Go Client in a docker container without changes and any problems since May 2017.

**Comment by alexwoz** [comment]
Hi, thanks for your message. We're aware of the issue and are working on a fix right now. I'll provide updates as the fix rolls out.

**Comment by colonelxc** [comment]
The fix has been fully rolled out. Please let us know if you have any issues.

**Comment by SvenAbels** [comment]
Works perfectly fine, :-)
