### ISSUE TITLE
Expose URL Parsing to Library Users

### ISSUE THREAD

**Issue by LegoRemix** [google/safebrowsing#72]
Hello!

As part of a user-safety project, I'm integrating google/safebrowsing into my employer's chat product as a means of filtering out harmful links. One difficulty we've run into is that our link parsing doesn't exactly line up with the library's. Specifically, we are using `https://github.com/mvdan/xurls` to find links in a chat message, and we then pass all of those links into the `SafeBrowser.LookupURLS` method. This has resulted in some infrequent, but regular edge-cases where the link parsing regex provided by `xurls`has a more expansive definition of a link than this library, leading to a `safebrowser : invalid path` errors.

I think the best, and easiest remediation for this would be if this library exposed a simple `IsURL` function, or provided an `ExtractUrls` method which would pull out all of the URLs in a string. That way, we could either filter out those URL-like strings which would cause an error, or just use this library's idea of what a URL is throughout our codebase.

Regards,
Ore Babarinsa.

**Comment by colonelxc** [comment]
Exposing parseUrl (or a wrapper around it) sounds reasonable. It's a bit of duplicate work for you, parsing then doing a lookup. It's also heavier than the regex solution from the xurls package.

Another solution (which was talked about in another issue) was creating exposed errors/error types that clients could match on easier. In this case, maybe it would return a ParseError which you could check via a type assertion. The problem with that for LookupURLs is that it takes a slice of URLs, but can return a single error. So you'd have to un-batch to get these benefits.

What do you think?

**Comment by LegoRemix** [comment]
I'd prefer the first solution, because we're parsing the URLs anyway to extract various components, so the rework isn't too much of an issue, whereas the latter would be a bit messy codewise, and we'd have to some rather strange error cases to handle such as what to do if one link in a message containing 3 links is not properly formatted.

**Comment by colonelxc** [comment]
Sorry for the delayed response! I've created a pull request that exposes a "IsURL" function. It doesn't necessarily eliminate the need to do some basic string splitting/regex work to find URLs (as explained in the commit), but would prevent getting a parse error when calling LookupURLs.
