### ISSUE TITLE
How can I trigger a fake Malware API response from my test suites?

### ISSUE THREAD

**Issue by kajmagnus** [google/safebrowsing#96]
Is there currently no way to dummy-trigger a harmful-URL response? So I can build Safe Browsing into my test suites?

I have an E2E tests suite, and I'd like to have the E2E test browser type a dummy "bad" URL, which my server sends to Safe Browsing API, and the API replies that the URL is harmful. So I can test my code that deals with *harmful URL* responses.

For example, Safe Browsing could return *"It's harmful & dangerous malware! For Windows!"* for all URLs like `https://safebrowsing-malware-windows.example.com`.

The Google Docs (https://developers.google.com/safe-browsing/v4/) doesn't mention any way to do this (that I can find). And in this GitHub repo I also didn't find any way to do that, or GitHub issue about that. This makes me surprised, because, reasonably, *everyone* who uses this API should want to make such dummy requsets from their test suites?

(I think there was, with API v3, but I cannot find those docs any longer)

**Comment by kajmagnus** [comment]
Now I found this: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/FrS3_AXV2R8

and seems to work, Chrome says this is malware:

`http://malware.testing.google.test/testing/malware/*`

How nice. I'll close this issue then.

**Comment by collimarco** [comment]
@kajmagnus It's not working for the Web Risk API, I don't get any warning. Any other URL that can trigger a warning?
